{
 "title": "Prod Eng App Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "greeting rated [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prod_eng_greeting_count_total[5m])"
    }
   ]
  },
  {
   "title": "greeting counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "prod_eng_greeting_count_total" }
   ]
  },
  {
   "title": "get greeting time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "prod_eng_greeting_time_seconds_max"
    }
   ]
  },
  {
   "title": "prod-eng rated [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(prod_eng_info_count_total[5m])"
    }
   ]
  },
  {
   "title": "prod-eng counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "prod_eng_info_count_total" }
   ]
  },
  {
   "title": "get prod-eng time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "prod_eng_info_time_seconds_max" }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_max"
    }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count"
    }
   ]
  },
  {
   "title": "spring_data_repository_invocations_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count"
    }
   ]
  }
 ]
}